<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerITKHqYm\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerITKHqYm/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerITKHqYm.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerITKHqYm\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerITKHqYm\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ITKHqYm',
    'container.build_id' => '2c8b7aef',
    'container.build_time' => 1521728470,
));
